-- ================================================================================
-- AUTO-GENERATED SQL SCRIPT - TẠO 404 TÀI KHOẢN
-- Cấu trúc: 4 PTGĐ → 16 GĐKD → 64 TLKD → 320 Giám sát
-- Generated by: generate_users.py
-- ================================================================================

-- ================================================================================
-- 1. TẠO 4 PTGĐ (Phó Tổng Giám Đốc)
-- ================================================================================

-- PTGĐ Bình Dương (ID: 17)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('ptgd_binhduong', '123456', 'Nguyễn Quốc Trung', 1, 1, '2020-01-15', NULL);

-- PTGĐ Hà Nội (ID: 18)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('ptgd_hanoi', '123456', 'Đỗ Đức Chí', 2, 1, '2020-01-15', NULL);

-- PTGĐ Hồ Chí Minh (ID: 19)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('ptgd_hochiminh', '123456', 'Vũ Quang Hoan', 4, 1, '2020-01-15', NULL);

-- PTGĐ Miền Trung (ID: 20)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('ptgd_mientrung', '123456', 'Lê Thị Bích Hạnh', 3, 1, '2020-01-15', NULL);


-- ================================================================================
-- 2. TẠO 16 GĐKD (4 GĐKD cho mỗi PTGĐ)
-- ================================================================================

-- GĐKD cho PTGĐ Bình Dương (IDs: 21-24)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gdkd_bd_01', '123456', 'Trần Văn An', 1, 2, '2020-05-01', 17);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gdkd_bd_02', '123456', 'Lê Thị Bình', 1, 2, '2020-06-01', 17);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gdkd_bd_03', '123456', 'Phạm Công Chi', 1, 2, '2020-07-01', 17);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gdkd_bd_04', '123456', 'Hoàng Minh Dung', 1, 2, '2020-08-01', 17);


-- GĐKD cho PTGĐ Hà Nội (IDs: 25-28)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gdkd_hn_01', '123456', 'Huỳnh Đức Giang', 2, 2, '2020-05-01', 18);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gdkd_hn_02', '123456', 'Phan Quốc Hà', 2, 2, '2020-06-01', 18);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gdkd_hn_03', '123456', 'Võ Hữu Hương', 2, 2, '2020-07-01', 18);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gdkd_hn_04', '123456', 'Đặng Thanh Khánh', 2, 2, '2020-08-01', 18);


-- GĐKD cho PTGĐ Hồ Chí Minh (IDs: 29-32)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gdkd_hcm_01', '123456', 'Bùi Ngọc Linh', 4, 2, '2020-05-01', 19);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gdkd_hcm_02', '123456', 'Đỗ Anh Mai', 4, 2, '2020-06-01', 19);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gdkd_hcm_03', '123456', 'Hồ Văn Nam', 4, 2, '2020-07-01', 19);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gdkd_hcm_04', '123456', 'Ngô Thị Oanh', 4, 2, '2020-08-01', 19);


-- GĐKD cho PTGĐ Miền Trung (IDs: 33-36)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gdkd_mt_01', '123456', 'Dương Công Phúc', 3, 2, '2020-05-01', 20);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gdkd_mt_02', '123456', 'Lý Minh Quỳnh', 3, 2, '2020-06-01', 20);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gdkd_mt_03', '123456', 'Vương Đức Sơn', 3, 2, '2020-07-01', 20);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gdkd_mt_04', '123456', 'Đinh Quốc Trang', 3, 2, '2020-08-01', 20);


-- ================================================================================
-- 3. TẠO 64 TLKD (4 TLKD cho mỗi GĐKD)
-- ================================================================================

-- TLKD cho GĐKD Bình Dương 01 (IDs: 37-40)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_bd_01_01', '123456', 'Trần Văn An', 1, 3, '2021-02-10', 21);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_bd_01_02', '123456', 'Lê Thị Bình', 1, 3, '2021-03-20', 21);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_bd_01_03', '123456', 'Phạm Công Chi', 1, 3, '2021-04-30', 21);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_bd_01_04', '123456', 'Hoàng Minh Dung', 1, 3, '2021-05-40', 21);


-- TLKD cho GĐKD Bình Dương 02 (IDs: 41-44)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_bd_02_01', '123456', 'Huỳnh Đức Giang', 1, 3, '2021-06-10', 22);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_bd_02_02', '123456', 'Phan Quốc Hà', 1, 3, '2021-07-20', 22);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_bd_02_03', '123456', 'Võ Hữu Hương', 1, 3, '2021-08-30', 22);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_bd_02_04', '123456', 'Đặng Thanh Khánh', 1, 3, '2021-09-40', 22);


-- TLKD cho GĐKD Bình Dương 03 (IDs: 45-48)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_bd_03_01', '123456', 'Bùi Ngọc Linh', 1, 3, '2021-10-10', 23);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_bd_03_02', '123456', 'Đỗ Anh Mai', 1, 3, '2021-11-20', 23);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_bd_03_03', '123456', 'Hồ Văn Nam', 1, 3, '2021-12-30', 23);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_bd_03_04', '123456', 'Ngô Thị Oanh', 1, 3, '2022-01-40', 23);


-- TLKD cho GĐKD Bình Dương 04 (IDs: 49-52)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_bd_04_01', '123456', 'Dương Công Phúc', 1, 3, '2022-02-10', 24);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_bd_04_02', '123456', 'Lý Minh Quỳnh', 1, 3, '2022-03-20', 24);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_bd_04_03', '123456', 'Vương Đức Sơn', 1, 3, '2022-04-30', 24);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_bd_04_04', '123456', 'Đinh Quốc Trang', 1, 3, '2022-05-40', 24);


-- TLKD cho GĐKD Hà Nội 01 (IDs: 53-56)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hn_01_01', '123456', 'Mai Hữu Uyên', 2, 3, '2022-06-10', 25);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hn_01_02', '123456', 'Lâm Thanh Vân', 2, 3, '2022-07-20', 25);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hn_01_03', '123456', 'Tạ Ngọc Xuân', 2, 3, '2022-08-30', 25);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hn_01_04', '123456', 'Cao Anh Yến', 2, 3, '2022-09-40', 25);


-- TLKD cho GĐKD Hà Nội 02 (IDs: 57-60)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hn_02_01', '123456', 'Trần Văn An', 2, 3, '2022-10-10', 26);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hn_02_02', '123456', 'Lê Thị Bình', 2, 3, '2022-11-20', 26);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hn_02_03', '123456', 'Phạm Công Chi', 2, 3, '2022-12-30', 26);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hn_02_04', '123456', 'Hoàng Minh Dung', 2, 3, '2023-01-40', 26);


-- TLKD cho GĐKD Hà Nội 03 (IDs: 61-64)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hn_03_01', '123456', 'Huỳnh Đức Giang', 2, 3, '2023-02-10', 27);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hn_03_02', '123456', 'Phan Quốc Hà', 2, 3, '2023-03-20', 27);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hn_03_03', '123456', 'Võ Hữu Hương', 2, 3, '2023-04-30', 27);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hn_03_04', '123456', 'Đặng Thanh Khánh', 2, 3, '2023-05-40', 27);


-- TLKD cho GĐKD Hà Nội 04 (IDs: 65-68)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hn_04_01', '123456', 'Bùi Ngọc Linh', 2, 3, '2023-06-10', 28);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hn_04_02', '123456', 'Đỗ Anh Mai', 2, 3, '2023-07-20', 28);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hn_04_03', '123456', 'Hồ Văn Nam', 2, 3, '2023-08-30', 28);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hn_04_04', '123456', 'Ngô Thị Oanh', 2, 3, '2023-09-40', 28);


-- TLKD cho GĐKD Hồ Chí Minh 01 (IDs: 69-72)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hcm_01_01', '123456', 'Dương Công Phúc', 4, 3, '2023-10-10', 29);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hcm_01_02', '123456', 'Lý Minh Quỳnh', 4, 3, '2023-11-20', 29);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hcm_01_03', '123456', 'Vương Đức Sơn', 4, 3, '2023-12-30', 29);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hcm_01_04', '123456', 'Đinh Quốc Trang', 4, 3, '2024-01-40', 29);


-- TLKD cho GĐKD Hồ Chí Minh 02 (IDs: 73-76)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hcm_02_01', '123456', 'Mai Hữu Uyên', 4, 3, '2024-02-10', 30);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hcm_02_02', '123456', 'Lâm Thanh Vân', 4, 3, '2024-03-20', 30);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hcm_02_03', '123456', 'Tạ Ngọc Xuân', 4, 3, '2024-04-30', 30);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hcm_02_04', '123456', 'Cao Anh Yến', 4, 3, '2024-05-40', 30);


-- TLKD cho GĐKD Hồ Chí Minh 03 (IDs: 77-80)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hcm_03_01', '123456', 'Trần Văn An', 4, 3, '2024-06-10', 31);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hcm_03_02', '123456', 'Lê Thị Bình', 4, 3, '2024-07-20', 31);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hcm_03_03', '123456', 'Phạm Công Chi', 4, 3, '2024-08-30', 31);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hcm_03_04', '123456', 'Hoàng Minh Dung', 4, 3, '2024-09-40', 31);


-- TLKD cho GĐKD Hồ Chí Minh 04 (IDs: 81-84)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hcm_04_01', '123456', 'Huỳnh Đức Giang', 4, 3, '2024-10-10', 32);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hcm_04_02', '123456', 'Phan Quốc Hà', 4, 3, '2024-11-20', 32);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hcm_04_03', '123456', 'Võ Hữu Hương', 4, 3, '2024-12-30', 32);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_hcm_04_04', '123456', 'Đặng Thanh Khánh', 4, 3, '2025-01-40', 32);


-- TLKD cho GĐKD Miền Trung 01 (IDs: 85-88)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_mt_01_01', '123456', 'Bùi Ngọc Linh', 3, 3, '2025-02-10', 33);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_mt_01_02', '123456', 'Đỗ Anh Mai', 3, 3, '2025-03-20', 33);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_mt_01_03', '123456', 'Hồ Văn Nam', 3, 3, '2025-04-30', 33);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_mt_01_04', '123456', 'Ngô Thị Oanh', 3, 3, '2025-05-40', 33);


-- TLKD cho GĐKD Miền Trung 02 (IDs: 89-92)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_mt_02_01', '123456', 'Dương Công Phúc', 3, 3, '2025-06-10', 34);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_mt_02_02', '123456', 'Lý Minh Quỳnh', 3, 3, '2025-07-20', 34);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_mt_02_03', '123456', 'Vương Đức Sơn', 3, 3, '2025-08-30', 34);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_mt_02_04', '123456', 'Đinh Quốc Trang', 3, 3, '2025-09-40', 34);


-- TLKD cho GĐKD Miền Trung 03 (IDs: 93-96)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_mt_03_01', '123456', 'Mai Hữu Uyên', 3, 3, '2025-10-10', 35);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_mt_03_02', '123456', 'Lâm Thanh Vân', 3, 3, '2025-11-20', 35);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_mt_03_03', '123456', 'Tạ Ngọc Xuân', 3, 3, '2025-12-30', 35);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_mt_03_04', '123456', 'Cao Anh Yến', 3, 3, '2026-01-40', 35);


-- TLKD cho GĐKD Miền Trung 04 (IDs: 97-100)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_mt_04_01', '123456', 'Trần Văn An', 3, 3, '2026-02-10', 36);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_mt_04_02', '123456', 'Lê Thị Bình', 3, 3, '2026-03-20', 36);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_mt_04_03', '123456', 'Phạm Công Chi', 3, 3, '2026-04-30', 36);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('tlkd_mt_04_04', '123456', 'Hoàng Minh Dung', 3, 3, '2026-05-40', 36);


-- ================================================================================
-- 4. TẠO 320 GIÁM SÁT (5 Giám sát cho mỗi TLKD)
-- ================================================================================

-- Giám sát cho TLKD BD 01 01 (IDs: 101-105)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_01_01', '123456', 'Test 1 Giám sát', 1, 4, '2022-10-20', 37);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_01_02', '123456', 'Test 2 Giám sát', 1, 4, '2022-11-01', 37);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_01_03', '123456', 'Test 3 Giám sát', 1, 4, '2022-11-11', 37);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_01_04', '123456', 'Test 4 Giám sát', 1, 4, '2022-11-21', 37);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_01_05', '123456', 'Test 5 Giám sát', 1, 4, '2022-12-01', 37);


-- Giám sát cho TLKD BD 01 02 (IDs: 106-110)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_02_01', '123456', 'Test 6 Giám sát', 1, 4, '2022-12-11', 38);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_02_02', '123456', 'Test 7 Giám sát', 1, 4, '2022-12-21', 38);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_02_03', '123456', 'Test 8 Giám sát', 1, 4, '2023-01-01', 38);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_02_04', '123456', 'Test 9 Giám sát', 1, 4, '2023-01-11', 38);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_02_05', '123456', 'Test 10 Giám sát', 1, 4, '2023-01-21', 38);


-- Giám sát cho TLKD BD 01 03 (IDs: 111-115)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_03_01', '123456', 'Test 11 Giám sát', 1, 4, '2023-02-01', 39);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_03_02', '123456', 'Test 12 Giám sát', 1, 4, '2023-02-11', 39);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_03_03', '123456', 'Test 13 Giám sát', 1, 4, '2023-02-21', 39);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_03_04', '123456', 'Test 14 Giám sát', 1, 4, '2023-03-01', 39);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_03_05', '123456', 'Test 15 Giám sát', 1, 4, '2023-03-11', 39);


-- Giám sát cho TLKD BD 01 04 (IDs: 116-120)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_04_01', '123456', 'Test 16 Giám sát', 1, 4, '2023-03-21', 40);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_04_02', '123456', 'Test 17 Giám sát', 1, 4, '2023-04-01', 40);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_04_03', '123456', 'Test 18 Giám sát', 1, 4, '2023-04-11', 40);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_04_04', '123456', 'Test 19 Giám sát', 1, 4, '2023-04-21', 40);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_01_04_05', '123456', 'Test 20 Giám sát', 1, 4, '2023-05-01', 40);


-- Giám sát cho TLKD BD 02 01 (IDs: 121-125)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_01_01', '123456', 'Test 21 Giám sát', 1, 4, '2023-05-11', 41);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_01_02', '123456', 'Test 22 Giám sát', 1, 4, '2023-05-21', 41);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_01_03', '123456', 'Test 23 Giám sát', 1, 4, '2023-06-01', 41);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_01_04', '123456', 'Test 24 Giám sát', 1, 4, '2023-06-11', 41);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_01_05', '123456', 'Test 25 Giám sát', 1, 4, '2023-06-21', 41);


-- Giám sát cho TLKD BD 02 02 (IDs: 126-130)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_02_01', '123456', 'Test 26 Giám sát', 1, 4, '2023-07-01', 42);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_02_02', '123456', 'Test 27 Giám sát', 1, 4, '2023-07-11', 42);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_02_03', '123456', 'Test 28 Giám sát', 1, 4, '2023-07-21', 42);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_02_04', '123456', 'Test 29 Giám sát', 1, 4, '2023-08-01', 42);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_02_05', '123456', 'Test 30 Giám sát', 1, 4, '2023-08-11', 42);


-- Giám sát cho TLKD BD 02 03 (IDs: 131-135)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_03_01', '123456', 'Test 31 Giám sát', 1, 4, '2023-08-21', 43);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_03_02', '123456', 'Test 32 Giám sát', 1, 4, '2023-09-01', 43);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_03_03', '123456', 'Test 33 Giám sát', 1, 4, '2023-09-11', 43);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_03_04', '123456', 'Test 34 Giám sát', 1, 4, '2023-09-21', 43);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_03_05', '123456', 'Test 35 Giám sát', 1, 4, '2023-10-01', 43);


-- Giám sát cho TLKD BD 02 04 (IDs: 136-140)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_04_01', '123456', 'Test 36 Giám sát', 1, 4, '2023-10-11', 44);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_04_02', '123456', 'Test 37 Giám sát', 1, 4, '2023-10-21', 44);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_04_03', '123456', 'Test 38 Giám sát', 1, 4, '2023-11-01', 44);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_04_04', '123456', 'Test 39 Giám sát', 1, 4, '2023-11-11', 44);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_02_04_05', '123456', 'Test 40 Giám sát', 1, 4, '2023-11-21', 44);


-- Giám sát cho TLKD BD 03 01 (IDs: 141-145)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_01_01', '123456', 'Test 41 Giám sát', 1, 4, '2023-12-01', 45);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_01_02', '123456', 'Test 42 Giám sát', 1, 4, '2023-12-11', 45);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_01_03', '123456', 'Test 43 Giám sát', 1, 4, '2023-12-21', 45);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_01_04', '123456', 'Test 44 Giám sát', 1, 4, '2024-01-01', 45);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_01_05', '123456', 'Test 45 Giám sát', 1, 4, '2024-01-11', 45);


-- Giám sát cho TLKD BD 03 02 (IDs: 146-150)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_02_01', '123456', 'Test 46 Giám sát', 1, 4, '2024-01-21', 46);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_02_02', '123456', 'Test 47 Giám sát', 1, 4, '2024-02-01', 46);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_02_03', '123456', 'Test 48 Giám sát', 1, 4, '2024-02-11', 46);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_02_04', '123456', 'Test 49 Giám sát', 1, 4, '2024-02-21', 46);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_02_05', '123456', 'Test 50 Giám sát', 1, 4, '2024-03-01', 46);


-- Giám sát cho TLKD BD 03 03 (IDs: 151-155)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_03_01', '123456', 'Test 51 Giám sát', 1, 4, '2024-03-11', 47);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_03_02', '123456', 'Test 52 Giám sát', 1, 4, '2024-03-21', 47);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_03_03', '123456', 'Test 53 Giám sát', 1, 4, '2024-04-01', 47);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_03_04', '123456', 'Test 54 Giám sát', 1, 4, '2024-04-11', 47);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_03_05', '123456', 'Test 55 Giám sát', 1, 4, '2024-04-21', 47);


-- Giám sát cho TLKD BD 03 04 (IDs: 156-160)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_04_01', '123456', 'Test 56 Giám sát', 1, 4, '2024-05-01', 48);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_04_02', '123456', 'Test 57 Giám sát', 1, 4, '2024-05-11', 48);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_04_03', '123456', 'Test 58 Giám sát', 1, 4, '2024-05-21', 48);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_04_04', '123456', 'Test 59 Giám sát', 1, 4, '2024-06-01', 48);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_03_04_05', '123456', 'Test 60 Giám sát', 1, 4, '2024-06-11', 48);


-- Giám sát cho TLKD BD 04 01 (IDs: 161-165)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_01_01', '123456', 'Test 61 Giám sát', 1, 4, '2024-06-21', 49);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_01_02', '123456', 'Test 62 Giám sát', 1, 4, '2024-07-01', 49);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_01_03', '123456', 'Test 63 Giám sát', 1, 4, '2024-07-11', 49);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_01_04', '123456', 'Test 64 Giám sát', 1, 4, '2024-07-21', 49);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_01_05', '123456', 'Test 65 Giám sát', 1, 4, '2024-08-01', 49);


-- Giám sát cho TLKD BD 04 02 (IDs: 166-170)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_02_01', '123456', 'Test 66 Giám sát', 1, 4, '2024-08-11', 50);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_02_02', '123456', 'Test 67 Giám sát', 1, 4, '2024-08-21', 50);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_02_03', '123456', 'Test 68 Giám sát', 1, 4, '2024-09-01', 50);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_02_04', '123456', 'Test 69 Giám sát', 1, 4, '2024-09-11', 50);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_02_05', '123456', 'Test 70 Giám sát', 1, 4, '2024-09-21', 50);


-- Giám sát cho TLKD BD 04 03 (IDs: 171-175)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_03_01', '123456', 'Test 71 Giám sát', 1, 4, '2024-10-01', 51);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_03_02', '123456', 'Test 72 Giám sát', 1, 4, '2024-10-11', 51);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_03_03', '123456', 'Test 73 Giám sát', 1, 4, '2024-10-21', 51);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_03_04', '123456', 'Test 74 Giám sát', 1, 4, '2024-11-01', 51);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_03_05', '123456', 'Test 75 Giám sát', 1, 4, '2024-11-11', 51);


-- Giám sát cho TLKD BD 04 04 (IDs: 176-180)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_04_01', '123456', 'Test 76 Giám sát', 1, 4, '2024-11-21', 52);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_04_02', '123456', 'Test 77 Giám sát', 1, 4, '2024-12-01', 52);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_04_03', '123456', 'Test 78 Giám sát', 1, 4, '2024-12-11', 52);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_04_04', '123456', 'Test 79 Giám sát', 1, 4, '2024-12-21', 52);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_bd_04_04_05', '123456', 'Test 80 Giám sát', 1, 4, '2025-01-01', 52);


-- Giám sát cho TLKD HN 01 01 (IDs: 181-185)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_01_01', '123456', 'Test 81 Giám sát', 2, 4, '2025-01-11', 53);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_01_02', '123456', 'Test 82 Giám sát', 2, 4, '2025-01-21', 53);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_01_03', '123456', 'Test 83 Giám sát', 2, 4, '2025-02-01', 53);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_01_04', '123456', 'Test 84 Giám sát', 2, 4, '2025-02-11', 53);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_01_05', '123456', 'Test 85 Giám sát', 2, 4, '2025-02-21', 53);


-- Giám sát cho TLKD HN 01 02 (IDs: 186-190)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_02_01', '123456', 'Test 86 Giám sát', 2, 4, '2025-03-01', 54);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_02_02', '123456', 'Test 87 Giám sát', 2, 4, '2025-03-11', 54);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_02_03', '123456', 'Test 88 Giám sát', 2, 4, '2025-03-21', 54);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_02_04', '123456', 'Test 89 Giám sát', 2, 4, '2025-04-01', 54);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_02_05', '123456', 'Test 90 Giám sát', 2, 4, '2025-04-11', 54);


-- Giám sát cho TLKD HN 01 03 (IDs: 191-195)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_03_01', '123456', 'Test 91 Giám sát', 2, 4, '2025-04-21', 55);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_03_02', '123456', 'Test 92 Giám sát', 2, 4, '2025-05-01', 55);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_03_03', '123456', 'Test 93 Giám sát', 2, 4, '2025-05-11', 55);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_03_04', '123456', 'Test 94 Giám sát', 2, 4, '2025-05-21', 55);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_03_05', '123456', 'Test 95 Giám sát', 2, 4, '2025-06-01', 55);


-- Giám sát cho TLKD HN 01 04 (IDs: 196-200)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_04_01', '123456', 'Test 96 Giám sát', 2, 4, '2025-06-11', 56);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_04_02', '123456', 'Test 97 Giám sát', 2, 4, '2025-06-21', 56);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_04_03', '123456', 'Test 98 Giám sát', 2, 4, '2025-07-01', 56);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_04_04', '123456', 'Test 99 Giám sát', 2, 4, '2025-07-11', 56);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_01_04_05', '123456', 'Test 100 Giám sát', 2, 4, '2025-07-21', 56);


-- Giám sát cho TLKD HN 02 01 (IDs: 201-205)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_01_01', '123456', 'Test 101 Giám sát', 2, 4, '2025-08-01', 57);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_01_02', '123456', 'Test 102 Giám sát', 2, 4, '2025-08-11', 57);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_01_03', '123456', 'Test 103 Giám sát', 2, 4, '2025-08-21', 57);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_01_04', '123456', 'Test 104 Giám sát', 2, 4, '2025-09-01', 57);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_01_05', '123456', 'Test 105 Giám sát', 2, 4, '2025-09-11', 57);


-- Giám sát cho TLKD HN 02 02 (IDs: 206-210)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_02_01', '123456', 'Test 106 Giám sát', 2, 4, '2025-09-21', 58);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_02_02', '123456', 'Test 107 Giám sát', 2, 4, '2025-10-01', 58);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_02_03', '123456', 'Test 108 Giám sát', 2, 4, '2025-10-11', 58);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_02_04', '123456', 'Test 109 Giám sát', 2, 4, '2025-10-21', 58);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_02_05', '123456', 'Test 110 Giám sát', 2, 4, '2025-11-01', 58);


-- Giám sát cho TLKD HN 02 03 (IDs: 211-215)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_03_01', '123456', 'Test 111 Giám sát', 2, 4, '2025-11-11', 59);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_03_02', '123456', 'Test 112 Giám sát', 2, 4, '2025-11-21', 59);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_03_03', '123456', 'Test 113 Giám sát', 2, 4, '2025-12-01', 59);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_03_04', '123456', 'Test 114 Giám sát', 2, 4, '2025-12-11', 59);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_03_05', '123456', 'Test 115 Giám sát', 2, 4, '2025-12-21', 59);


-- Giám sát cho TLKD HN 02 04 (IDs: 216-220)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_04_01', '123456', 'Test 116 Giám sát', 2, 4, '2026-01-01', 60);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_04_02', '123456', 'Test 117 Giám sát', 2, 4, '2026-01-11', 60);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_04_03', '123456', 'Test 118 Giám sát', 2, 4, '2026-01-21', 60);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_04_04', '123456', 'Test 119 Giám sát', 2, 4, '2026-02-01', 60);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_02_04_05', '123456', 'Test 120 Giám sát', 2, 4, '2026-02-11', 60);


-- Giám sát cho TLKD HN 03 01 (IDs: 221-225)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_01_01', '123456', 'Test 121 Giám sát', 2, 4, '2026-02-21', 61);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_01_02', '123456', 'Test 122 Giám sát', 2, 4, '2026-03-01', 61);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_01_03', '123456', 'Test 123 Giám sát', 2, 4, '2026-03-11', 61);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_01_04', '123456', 'Test 124 Giám sát', 2, 4, '2026-03-21', 61);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_01_05', '123456', 'Test 125 Giám sát', 2, 4, '2026-04-01', 61);


-- Giám sát cho TLKD HN 03 02 (IDs: 226-230)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_02_01', '123456', 'Test 126 Giám sát', 2, 4, '2026-04-11', 62);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_02_02', '123456', 'Test 127 Giám sát', 2, 4, '2026-04-21', 62);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_02_03', '123456', 'Test 128 Giám sát', 2, 4, '2026-05-01', 62);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_02_04', '123456', 'Test 129 Giám sát', 2, 4, '2026-05-11', 62);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_02_05', '123456', 'Test 130 Giám sát', 2, 4, '2026-05-21', 62);


-- Giám sát cho TLKD HN 03 03 (IDs: 231-235)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_03_01', '123456', 'Test 131 Giám sát', 2, 4, '2026-06-01', 63);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_03_02', '123456', 'Test 132 Giám sát', 2, 4, '2026-06-11', 63);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_03_03', '123456', 'Test 133 Giám sát', 2, 4, '2026-06-21', 63);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_03_04', '123456', 'Test 134 Giám sát', 2, 4, '2026-07-01', 63);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_03_05', '123456', 'Test 135 Giám sát', 2, 4, '2026-07-11', 63);


-- Giám sát cho TLKD HN 03 04 (IDs: 236-240)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_04_01', '123456', 'Test 136 Giám sát', 2, 4, '2026-07-21', 64);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_04_02', '123456', 'Test 137 Giám sát', 2, 4, '2026-08-01', 64);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_04_03', '123456', 'Test 138 Giám sát', 2, 4, '2026-08-11', 64);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_04_04', '123456', 'Test 139 Giám sát', 2, 4, '2026-08-21', 64);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_03_04_05', '123456', 'Test 140 Giám sát', 2, 4, '2026-09-01', 64);


-- Giám sát cho TLKD HN 04 01 (IDs: 241-245)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_01_01', '123456', 'Test 141 Giám sát', 2, 4, '2026-09-11', 65);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_01_02', '123456', 'Test 142 Giám sát', 2, 4, '2026-09-21', 65);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_01_03', '123456', 'Test 143 Giám sát', 2, 4, '2026-10-01', 65);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_01_04', '123456', 'Test 144 Giám sát', 2, 4, '2026-10-11', 65);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_01_05', '123456', 'Test 145 Giám sát', 2, 4, '2026-10-21', 65);


-- Giám sát cho TLKD HN 04 02 (IDs: 246-250)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_02_01', '123456', 'Test 146 Giám sát', 2, 4, '2026-11-01', 66);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_02_02', '123456', 'Test 147 Giám sát', 2, 4, '2026-11-11', 66);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_02_03', '123456', 'Test 148 Giám sát', 2, 4, '2026-11-21', 66);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_02_04', '123456', 'Test 149 Giám sát', 2, 4, '2026-12-01', 66);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_02_05', '123456', 'Test 150 Giám sát', 2, 4, '2026-12-11', 66);


-- Giám sát cho TLKD HN 04 03 (IDs: 251-255)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_03_01', '123456', 'Test 151 Giám sát', 2, 4, '2026-12-21', 67);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_03_02', '123456', 'Test 152 Giám sát', 2, 4, '2027-01-01', 67);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_03_03', '123456', 'Test 153 Giám sát', 2, 4, '2027-01-11', 67);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_03_04', '123456', 'Test 154 Giám sát', 2, 4, '2027-01-21', 67);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_03_05', '123456', 'Test 155 Giám sát', 2, 4, '2027-02-01', 67);


-- Giám sát cho TLKD HN 04 04 (IDs: 256-260)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_04_01', '123456', 'Test 156 Giám sát', 2, 4, '2027-02-11', 68);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_04_02', '123456', 'Test 157 Giám sát', 2, 4, '2027-02-21', 68);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_04_03', '123456', 'Test 158 Giám sát', 2, 4, '2027-03-01', 68);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_04_04', '123456', 'Test 159 Giám sát', 2, 4, '2027-03-11', 68);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hn_04_04_05', '123456', 'Test 160 Giám sát', 2, 4, '2027-03-21', 68);


-- Giám sát cho TLKD HCM 01 01 (IDs: 261-265)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_01_01', '123456', 'Test 161 Giám sát', 4, 4, '2027-04-01', 69);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_01_02', '123456', 'Test 162 Giám sát', 4, 4, '2027-04-11', 69);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_01_03', '123456', 'Test 163 Giám sát', 4, 4, '2027-04-21', 69);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_01_04', '123456', 'Test 164 Giám sát', 4, 4, '2027-05-01', 69);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_01_05', '123456', 'Test 165 Giám sát', 4, 4, '2027-05-11', 69);


-- Giám sát cho TLKD HCM 01 02 (IDs: 266-270)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_02_01', '123456', 'Test 166 Giám sát', 4, 4, '2027-05-21', 70);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_02_02', '123456', 'Test 167 Giám sát', 4, 4, '2027-06-01', 70);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_02_03', '123456', 'Test 168 Giám sát', 4, 4, '2027-06-11', 70);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_02_04', '123456', 'Test 169 Giám sát', 4, 4, '2027-06-21', 70);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_02_05', '123456', 'Test 170 Giám sát', 4, 4, '2027-07-01', 70);


-- Giám sát cho TLKD HCM 01 03 (IDs: 271-275)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_03_01', '123456', 'Test 171 Giám sát', 4, 4, '2027-07-11', 71);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_03_02', '123456', 'Test 172 Giám sát', 4, 4, '2027-07-21', 71);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_03_03', '123456', 'Test 173 Giám sát', 4, 4, '2027-08-01', 71);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_03_04', '123456', 'Test 174 Giám sát', 4, 4, '2027-08-11', 71);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_03_05', '123456', 'Test 175 Giám sát', 4, 4, '2027-08-21', 71);


-- Giám sát cho TLKD HCM 01 04 (IDs: 276-280)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_04_01', '123456', 'Test 176 Giám sát', 4, 4, '2027-09-01', 72);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_04_02', '123456', 'Test 177 Giám sát', 4, 4, '2027-09-11', 72);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_04_03', '123456', 'Test 178 Giám sát', 4, 4, '2027-09-21', 72);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_04_04', '123456', 'Test 179 Giám sát', 4, 4, '2027-10-01', 72);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_01_04_05', '123456', 'Test 180 Giám sát', 4, 4, '2027-10-11', 72);


-- Giám sát cho TLKD HCM 02 01 (IDs: 281-285)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_01_01', '123456', 'Test 181 Giám sát', 4, 4, '2027-10-21', 73);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_01_02', '123456', 'Test 182 Giám sát', 4, 4, '2027-11-01', 73);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_01_03', '123456', 'Test 183 Giám sát', 4, 4, '2027-11-11', 73);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_01_04', '123456', 'Test 184 Giám sát', 4, 4, '2027-11-21', 73);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_01_05', '123456', 'Test 185 Giám sát', 4, 4, '2027-12-01', 73);


-- Giám sát cho TLKD HCM 02 02 (IDs: 286-290)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_02_01', '123456', 'Test 186 Giám sát', 4, 4, '2027-12-11', 74);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_02_02', '123456', 'Test 187 Giám sát', 4, 4, '2027-12-21', 74);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_02_03', '123456', 'Test 188 Giám sát', 4, 4, '2028-01-01', 74);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_02_04', '123456', 'Test 189 Giám sát', 4, 4, '2028-01-11', 74);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_02_05', '123456', 'Test 190 Giám sát', 4, 4, '2028-01-21', 74);


-- Giám sát cho TLKD HCM 02 03 (IDs: 291-295)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_03_01', '123456', 'Test 191 Giám sát', 4, 4, '2028-02-01', 75);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_03_02', '123456', 'Test 192 Giám sát', 4, 4, '2028-02-11', 75);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_03_03', '123456', 'Test 193 Giám sát', 4, 4, '2028-02-21', 75);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_03_04', '123456', 'Test 194 Giám sát', 4, 4, '2028-03-01', 75);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_03_05', '123456', 'Test 195 Giám sát', 4, 4, '2028-03-11', 75);


-- Giám sát cho TLKD HCM 02 04 (IDs: 296-300)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_04_01', '123456', 'Test 196 Giám sát', 4, 4, '2028-03-21', 76);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_04_02', '123456', 'Test 197 Giám sát', 4, 4, '2028-04-01', 76);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_04_03', '123456', 'Test 198 Giám sát', 4, 4, '2028-04-11', 76);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_04_04', '123456', 'Test 199 Giám sát', 4, 4, '2028-04-21', 76);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_02_04_05', '123456', 'Test 200 Giám sát', 4, 4, '2028-05-01', 76);


-- Giám sát cho TLKD HCM 03 01 (IDs: 301-305)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_01_01', '123456', 'Test 201 Giám sát', 4, 4, '2028-05-11', 77);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_01_02', '123456', 'Test 202 Giám sát', 4, 4, '2028-05-21', 77);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_01_03', '123456', 'Test 203 Giám sát', 4, 4, '2028-06-01', 77);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_01_04', '123456', 'Test 204 Giám sát', 4, 4, '2028-06-11', 77);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_01_05', '123456', 'Test 205 Giám sát', 4, 4, '2028-06-21', 77);


-- Giám sát cho TLKD HCM 03 02 (IDs: 306-310)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_02_01', '123456', 'Test 206 Giám sát', 4, 4, '2028-07-01', 78);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_02_02', '123456', 'Test 207 Giám sát', 4, 4, '2028-07-11', 78);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_02_03', '123456', 'Test 208 Giám sát', 4, 4, '2028-07-21', 78);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_02_04', '123456', 'Test 209 Giám sát', 4, 4, '2028-08-01', 78);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_02_05', '123456', 'Test 210 Giám sát', 4, 4, '2028-08-11', 78);


-- Giám sát cho TLKD HCM 03 03 (IDs: 311-315)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_03_01', '123456', 'Test 211 Giám sát', 4, 4, '2028-08-21', 79);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_03_02', '123456', 'Test 212 Giám sát', 4, 4, '2028-09-01', 79);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_03_03', '123456', 'Test 213 Giám sát', 4, 4, '2028-09-11', 79);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_03_04', '123456', 'Test 214 Giám sát', 4, 4, '2028-09-21', 79);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_03_05', '123456', 'Test 215 Giám sát', 4, 4, '2028-10-01', 79);


-- Giám sát cho TLKD HCM 03 04 (IDs: 316-320)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_04_01', '123456', 'Test 216 Giám sát', 4, 4, '2028-10-11', 80);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_04_02', '123456', 'Test 217 Giám sát', 4, 4, '2028-10-21', 80);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_04_03', '123456', 'Test 218 Giám sát', 4, 4, '2028-11-01', 80);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_04_04', '123456', 'Test 219 Giám sát', 4, 4, '2028-11-11', 80);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_03_04_05', '123456', 'Test 220 Giám sát', 4, 4, '2028-11-21', 80);


-- Giám sát cho TLKD HCM 04 01 (IDs: 321-325)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_01_01', '123456', 'Test 221 Giám sát', 4, 4, '2028-12-01', 81);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_01_02', '123456', 'Test 222 Giám sát', 4, 4, '2028-12-11', 81);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_01_03', '123456', 'Test 223 Giám sát', 4, 4, '2028-12-21', 81);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_01_04', '123456', 'Test 224 Giám sát', 4, 4, '2029-01-01', 81);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_01_05', '123456', 'Test 225 Giám sát', 4, 4, '2029-01-11', 81);


-- Giám sát cho TLKD HCM 04 02 (IDs: 326-330)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_02_01', '123456', 'Test 226 Giám sát', 4, 4, '2029-01-21', 82);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_02_02', '123456', 'Test 227 Giám sát', 4, 4, '2029-02-01', 82);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_02_03', '123456', 'Test 228 Giám sát', 4, 4, '2029-02-11', 82);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_02_04', '123456', 'Test 229 Giám sát', 4, 4, '2029-02-21', 82);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_02_05', '123456', 'Test 230 Giám sát', 4, 4, '2029-03-01', 82);


-- Giám sát cho TLKD HCM 04 03 (IDs: 331-335)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_03_01', '123456', 'Test 231 Giám sát', 4, 4, '2029-03-11', 83);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_03_02', '123456', 'Test 232 Giám sát', 4, 4, '2029-03-21', 83);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_03_03', '123456', 'Test 233 Giám sát', 4, 4, '2029-04-01', 83);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_03_04', '123456', 'Test 234 Giám sát', 4, 4, '2029-04-11', 83);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_03_05', '123456', 'Test 235 Giám sát', 4, 4, '2029-04-21', 83);


-- Giám sát cho TLKD HCM 04 04 (IDs: 336-340)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_04_01', '123456', 'Test 236 Giám sát', 4, 4, '2029-05-01', 84);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_04_02', '123456', 'Test 237 Giám sát', 4, 4, '2029-05-11', 84);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_04_03', '123456', 'Test 238 Giám sát', 4, 4, '2029-05-21', 84);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_04_04', '123456', 'Test 239 Giám sát', 4, 4, '2029-06-01', 84);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_hcm_04_04_05', '123456', 'Test 240 Giám sát', 4, 4, '2029-06-11', 84);


-- Giám sát cho TLKD MT 01 01 (IDs: 341-345)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_01_01', '123456', 'Test 241 Giám sát', 3, 4, '2029-06-21', 85);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_01_02', '123456', 'Test 242 Giám sát', 3, 4, '2029-07-01', 85);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_01_03', '123456', 'Test 243 Giám sát', 3, 4, '2029-07-11', 85);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_01_04', '123456', 'Test 244 Giám sát', 3, 4, '2029-07-21', 85);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_01_05', '123456', 'Test 245 Giám sát', 3, 4, '2029-08-01', 85);


-- Giám sát cho TLKD MT 01 02 (IDs: 346-350)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_02_01', '123456', 'Test 246 Giám sát', 3, 4, '2029-08-11', 86);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_02_02', '123456', 'Test 247 Giám sát', 3, 4, '2029-08-21', 86);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_02_03', '123456', 'Test 248 Giám sát', 3, 4, '2029-09-01', 86);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_02_04', '123456', 'Test 249 Giám sát', 3, 4, '2029-09-11', 86);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_02_05', '123456', 'Test 250 Giám sát', 3, 4, '2029-09-21', 86);


-- Giám sát cho TLKD MT 01 03 (IDs: 351-355)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_03_01', '123456', 'Test 251 Giám sát', 3, 4, '2029-10-01', 87);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_03_02', '123456', 'Test 252 Giám sát', 3, 4, '2029-10-11', 87);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_03_03', '123456', 'Test 253 Giám sát', 3, 4, '2029-10-21', 87);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_03_04', '123456', 'Test 254 Giám sát', 3, 4, '2029-11-01', 87);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_03_05', '123456', 'Test 255 Giám sát', 3, 4, '2029-11-11', 87);


-- Giám sát cho TLKD MT 01 04 (IDs: 356-360)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_04_01', '123456', 'Test 256 Giám sát', 3, 4, '2029-11-21', 88);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_04_02', '123456', 'Test 257 Giám sát', 3, 4, '2029-12-01', 88);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_04_03', '123456', 'Test 258 Giám sát', 3, 4, '2029-12-11', 88);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_04_04', '123456', 'Test 259 Giám sát', 3, 4, '2029-12-21', 88);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_01_04_05', '123456', 'Test 260 Giám sát', 3, 4, '2030-01-01', 88);


-- Giám sát cho TLKD MT 02 01 (IDs: 361-365)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_01_01', '123456', 'Test 261 Giám sát', 3, 4, '2030-01-11', 89);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_01_02', '123456', 'Test 262 Giám sát', 3, 4, '2030-01-21', 89);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_01_03', '123456', 'Test 263 Giám sát', 3, 4, '2030-02-01', 89);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_01_04', '123456', 'Test 264 Giám sát', 3, 4, '2030-02-11', 89);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_01_05', '123456', 'Test 265 Giám sát', 3, 4, '2030-02-21', 89);


-- Giám sát cho TLKD MT 02 02 (IDs: 366-370)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_02_01', '123456', 'Test 266 Giám sát', 3, 4, '2030-03-01', 90);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_02_02', '123456', 'Test 267 Giám sát', 3, 4, '2030-03-11', 90);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_02_03', '123456', 'Test 268 Giám sát', 3, 4, '2030-03-21', 90);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_02_04', '123456', 'Test 269 Giám sát', 3, 4, '2030-04-01', 90);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_02_05', '123456', 'Test 270 Giám sát', 3, 4, '2030-04-11', 90);


-- Giám sát cho TLKD MT 02 03 (IDs: 371-375)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_03_01', '123456', 'Test 271 Giám sát', 3, 4, '2030-04-21', 91);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_03_02', '123456', 'Test 272 Giám sát', 3, 4, '2030-05-01', 91);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_03_03', '123456', 'Test 273 Giám sát', 3, 4, '2030-05-11', 91);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_03_04', '123456', 'Test 274 Giám sát', 3, 4, '2030-05-21', 91);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_03_05', '123456', 'Test 275 Giám sát', 3, 4, '2030-06-01', 91);


-- Giám sát cho TLKD MT 02 04 (IDs: 376-380)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_04_01', '123456', 'Test 276 Giám sát', 3, 4, '2030-06-11', 92);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_04_02', '123456', 'Test 277 Giám sát', 3, 4, '2030-06-21', 92);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_04_03', '123456', 'Test 278 Giám sát', 3, 4, '2030-07-01', 92);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_04_04', '123456', 'Test 279 Giám sát', 3, 4, '2030-07-11', 92);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_02_04_05', '123456', 'Test 280 Giám sát', 3, 4, '2030-07-21', 92);


-- Giám sát cho TLKD MT 03 01 (IDs: 381-385)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_01_01', '123456', 'Test 281 Giám sát', 3, 4, '2030-08-01', 93);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_01_02', '123456', 'Test 282 Giám sát', 3, 4, '2030-08-11', 93);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_01_03', '123456', 'Test 283 Giám sát', 3, 4, '2030-08-21', 93);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_01_04', '123456', 'Test 284 Giám sát', 3, 4, '2030-09-01', 93);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_01_05', '123456', 'Test 285 Giám sát', 3, 4, '2030-09-11', 93);


-- Giám sát cho TLKD MT 03 02 (IDs: 386-390)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_02_01', '123456', 'Test 286 Giám sát', 3, 4, '2030-09-21', 94);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_02_02', '123456', 'Test 287 Giám sát', 3, 4, '2030-10-01', 94);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_02_03', '123456', 'Test 288 Giám sát', 3, 4, '2030-10-11', 94);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_02_04', '123456', 'Test 289 Giám sát', 3, 4, '2030-10-21', 94);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_02_05', '123456', 'Test 290 Giám sát', 3, 4, '2030-11-01', 94);


-- Giám sát cho TLKD MT 03 03 (IDs: 391-395)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_03_01', '123456', 'Test 291 Giám sát', 3, 4, '2030-11-11', 95);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_03_02', '123456', 'Test 292 Giám sát', 3, 4, '2030-11-21', 95);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_03_03', '123456', 'Test 293 Giám sát', 3, 4, '2030-12-01', 95);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_03_04', '123456', 'Test 294 Giám sát', 3, 4, '2030-12-11', 95);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_03_05', '123456', 'Test 295 Giám sát', 3, 4, '2030-12-21', 95);


-- Giám sát cho TLKD MT 03 04 (IDs: 396-400)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_04_01', '123456', 'Test 296 Giám sát', 3, 4, '2031-01-01', 96);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_04_02', '123456', 'Test 297 Giám sát', 3, 4, '2031-01-11', 96);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_04_03', '123456', 'Test 298 Giám sát', 3, 4, '2031-01-21', 96);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_04_04', '123456', 'Test 299 Giám sát', 3, 4, '2031-02-01', 96);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_03_04_05', '123456', 'Test 300 Giám sát', 3, 4, '2031-02-11', 96);


-- Giám sát cho TLKD MT 04 01 (IDs: 401-405)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_01_01', '123456', 'Test 301 Giám sát', 3, 4, '2031-02-21', 97);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_01_02', '123456', 'Test 302 Giám sát', 3, 4, '2031-03-01', 97);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_01_03', '123456', 'Test 303 Giám sát', 3, 4, '2031-03-11', 97);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_01_04', '123456', 'Test 304 Giám sát', 3, 4, '2031-03-21', 97);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_01_05', '123456', 'Test 305 Giám sát', 3, 4, '2031-04-01', 97);


-- Giám sát cho TLKD MT 04 02 (IDs: 406-410)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_02_01', '123456', 'Test 306 Giám sát', 3, 4, '2031-04-11', 98);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_02_02', '123456', 'Test 307 Giám sát', 3, 4, '2031-04-21', 98);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_02_03', '123456', 'Test 308 Giám sát', 3, 4, '2031-05-01', 98);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_02_04', '123456', 'Test 309 Giám sát', 3, 4, '2031-05-11', 98);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_02_05', '123456', 'Test 310 Giám sát', 3, 4, '2031-05-21', 98);


-- Giám sát cho TLKD MT 04 03 (IDs: 411-415)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_03_01', '123456', 'Test 311 Giám sát', 3, 4, '2031-06-01', 99);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_03_02', '123456', 'Test 312 Giám sát', 3, 4, '2031-06-11', 99);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_03_03', '123456', 'Test 313 Giám sát', 3, 4, '2031-06-21', 99);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_03_04', '123456', 'Test 314 Giám sát', 3, 4, '2031-07-01', 99);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_03_05', '123456', 'Test 315 Giám sát', 3, 4, '2031-07-11', 99);


-- Giám sát cho TLKD MT 04 04 (IDs: 416-420)
INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_04_01', '123456', 'Test 316 Giám sát', 3, 4, '2031-07-21', 100);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_04_02', '123456', 'Test 317 Giám sát', 3, 4, '2031-08-01', 100);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_04_03', '123456', 'Test 318 Giám sát', 3, 4, '2031-08-11', 100);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_04_04', '123456', 'Test 319 Giám sát', 3, 4, '2031-08-21', 100);

INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)
VALUES ('gs_mt_04_04_05', '123456', 'Test 320 Giám sát', 3, 4, '2031-09-01', 100);


-- ================================================================================
-- TỔNG SỐ TÀI KHOẢN ĐÃ TẠO: 404
-- 4 PTGĐ + 16 GĐKD + 64 TLKD + 320 Giám sát = 404 tài khoản
-- Mật khẩu mặc định: 123456
-- ================================================================================