#!/usr/bin/env python3
"""
Generate SQL script to create all 404 user accounts
Structure: 4 PTGĐ → 16 GĐKD → 64 TLKD → 320 Giám sát
"""

# Region mapping
regions = {
    'bd': {'id': 1, 'name': 'Bình Dương', 'short': 'bd'},
    'hn': {'id': 2, 'name': 'Hà Nội', 'short': 'hn'},
    'mt': {'id': 3, 'name': 'Miền Trung', 'short': 'mt'},
    'hcm': {'id': 4, 'name': 'Hồ Chí Minh', 'short': 'hcm'}
}

# PTGĐ list from image
ptgd_list = [
    {'name': 'Nguyễn Quốc Trung', 'region': 'bd', 'username': 'ptgd_binhduong'},
    {'name': 'Đỗ Đức Chí', 'region': 'hn', 'username': 'ptgd_hanoi'},
    {'name': 'Vũ Quang Hoan', 'region': 'hcm', 'username': 'ptgd_hochiminh'},
    {'name': 'Lê Thị Bích Hạnh', 'region': 'mt', 'username': 'ptgd_mientrung'}
]

# Vietnamese surnames
surnames = ['Trần', 'Lê', 'Phạm', 'Hoàng', 'Huỳnh', 'Phan', 'Võ', 'Đặng', 'Bùi', 'Đỗ',
            'Hồ', 'Ngô', 'Dương', 'Lý', 'Vương', 'Đinh', 'Mai', 'Lâm', 'Tạ', 'Cao']

middle_names = ['Văn', 'Thị', 'Công', 'Minh', 'Đức', 'Quốc', 'Hữu', 'Thanh', 'Ngọc', 'Anh']

given_names = ['An', 'Bình', 'Chi', 'Dung', 'Giang', 'Hà', 'Hương', 'Khánh', 'Linh', 'Mai',
               'Nam', 'Oanh', 'Phúc', 'Quỳnh', 'Sơn', 'Trang', 'Uyên', 'Vân', 'Xuân', 'Yến']

# SQL template
INSERT_TEMPLATE = "INSERT INTO users (username, password, full_name, region_id, position_id, start_date, manager_id)\nVALUES ('{}', '123456', '{}', {}, {}, '{}', {});\n"

def generate_name(index):
    """Generate Vietnamese full name"""
    surname = surnames[index % len(surnames)]
    middle = middle_names[index % len(middle_names)]
    given = given_names[index % len(given_names)]
    return f"{surname} {middle} {given}"

def main():
    output = []
    output.append("-- " + "="*80)
    output.append("-- AUTO-GENERATED SQL SCRIPT - TẠO 404 TÀI KHOẢN")
    output.append("-- Cấu trúc: 4 PTGĐ → 16 GĐKD → 64 TLKD → 320 Giám sát")
    output.append("-- Generated by: generate_users.py")
    output.append("-- " + "="*80 + "\n")
    
    current_user_id = 17  # Start from ID 17 (after existing 16 users + admin)
    
    # ===== 1. CREATE 4 PTGĐ =====
    output.append("-- " + "="*80)
    output.append("-- 1. TẠO 4 PTGĐ (Phó Tổng Giám Đốc)")
    output.append("-- " + "="*80 + "\n")
    
    ptgd_ids = {}
    for ptgd in ptgd_list:
        region_id = regions[ptgd['region']]['id']
        output.append(f"-- PTGĐ {regions[ptgd['region']]['name']} (ID: {current_user_id})")
        output.append(INSERT_TEMPLATE.format(
            ptgd['username'],
            ptgd['name'],
            region_id,
            1,  # position_id for PTGĐ
            '2020-01-15',
            'NULL'  # No manager
        ))
        ptgd_ids[ptgd['region']] = current_user_id
        current_user_id += 1
    
    output.append("")
    
    # ===== 2. CREATE 16 GĐKD (4 per PTGĐ) =====
    output.append("-- " + "="*80)
    output.append("-- 2. TẠO 16 GĐKD (4 GĐKD cho mỗi PTGĐ)")
    output.append("-- " + "="*80 + "\n")
    
    gdkd_ids = {}
    gdkd_count = 0
    
    for region_key in ['bd', 'hn', 'hcm', 'mt']:
        region = regions[region_key]
        gdkd_ids[region_key] = []
        
        output.append(f"-- GĐKD cho PTGĐ {region['name']} (IDs: {current_user_id}-{current_user_id+3})")
        
        for i in range(4):
            username = f"gdkd_{region['short']}_{i+1:02d}"
            full_name = generate_name(gdkd_count)
            
            output.append(INSERT_TEMPLATE.format(
                username,
                full_name,
                region['id'],
                2,  # position_id for GĐKD
                f"2020-{5+i:02d}-01",
                ptgd_ids[region_key]
            ))
            
            gdkd_ids[region_key].append(current_user_id)
            current_user_id += 1
            gdkd_count += 1
        
        output.append("")
    
    # ===== 3. CREATE 64 TLKD (4 per GĐKD) =====
    output.append("-- " + "="*80)
    output.append("-- 3. TẠO 64 TLKD (4 TLKD cho mỗi GĐKD)")
    output.append("-- " + "="*80 + "\n")
    
    tlkd_ids = {}
    tlkd_count = 0
    month_counter = 1
    
    for region_key in ['bd', 'hn', 'hcm', 'mt']:
        region = regions[region_key]
        tlkd_ids[region_key] = []
        
        for gdkd_idx, gdkd_id in enumerate(gdkd_ids[region_key]):
            tlkd_ids[region_key].append([])
            
            output.append(f"-- TLKD cho GĐKD {region['name']} {gdkd_idx+1:02d} (IDs: {current_user_id}-{current_user_id+3})")
            
            for i in range(4):
                username = f"tlkd_{region['short']}_{gdkd_idx+1:02d}_{i+1:02d}"
                full_name = generate_name(tlkd_count)
                
                year = 2021 + (month_counter // 12)
                month = (month_counter % 12) + 1
                
                output.append(INSERT_TEMPLATE.format(
                    username,
                    full_name,
                    region['id'],
                    3,  # position_id for TLKD
                    f"{year}-{month:02d}-{(i+1)*10:02d}",
                    gdkd_id
                ))
                
                tlkd_ids[region_key][-1].append(current_user_id)
                current_user_id += 1
                tlkd_count += 1
                month_counter += 1
            
            output.append("")
    
    # ===== 4. CREATE 320 GIÁM SÁT (5 per TLKD) =====
    output.append("-- " + "="*80)
    output.append("-- 4. TẠO 320 GIÁM SÁT (5 Giám sát cho mỗi TLKD)")
    output.append("-- " + "="*80 + "\n")
    
    gs_count = 1
    year = 2022
    month = 10
    day = 20
    
    for region_key in ['bd', 'hn', 'hcm', 'mt']:
        region = regions[region_key]
        
        for gdkd_idx, gdkd_tlkd_list in enumerate(tlkd_ids[region_key]):
            for tlkd_idx, tlkd_id in enumerate(gdkd_tlkd_list):
                output.append(f"-- Giám sát cho TLKD {region['short'].upper()} {gdkd_idx+1:02d} {tlkd_idx+1:02d} (IDs: {current_user_id}-{current_user_id+4})")
                
                for i in range(5):
                    username = f"gs_{region['short']}_{gdkd_idx+1:02d}_{tlkd_idx+1:02d}_{i+1:02d}"
                    full_name = f"Test {gs_count} Giám sát"
                    
                    output.append(INSERT_TEMPLATE.format(
                        username,
                        full_name,
                        region['id'],
                        4,  # position_id for Giám sát
                        f"{year}-{month:02d}-{day:02d}",
                        tlkd_id
                    ))
                    
                    current_user_id += 1
                    gs_count += 1
                    
                    # Increment date
                    day += 10
                    if day > 28:
                        day = 1
                        month += 1
                        if month > 12:
                            month = 1
                            year += 1
                
                output.append("")
    
    # Summary
    output.append("-- " + "="*80)
    output.append(f"-- TỔNG SỐ TÀI KHOẢN ĐÃ TẠO: {current_user_id - 17}")
    output.append(f"-- 4 PTGĐ + 16 GĐKD + 64 TLKD + 320 Giám sát = {current_user_id - 17} tài khoản")
    output.append("-- Mật khẩu mặc định: 123456")
    output.append("-- " + "="*80)
    
    # Write to file
    with open('/home/user/webapp/create_all_users_full.sql', 'w', encoding='utf-8') as f:
        f.write('\n'.join(output))
    
    print(f"✅ Generated SQL script with {current_user_id - 17} users")
    print(f"   - 4 PTGĐ")
    print(f"   - 16 GĐKD")
    print(f"   - 64 TLKD")
    print(f"   - 320 Giám sát")
    print(f"   Total: {current_user_id - 17} users")
    print(f"\n📁 Output file: /home/user/webapp/create_all_users_full.sql")

if __name__ == '__main__':
    main()
